### ISSUE TITLE
little error

### ISSUE THREAD

**Issue by goldenplan** [theyakka/fluro#147] opened 2020-02-08 07:57 UTC
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/fluro-1.5.1/lib/src/router.dart:41:47: Error: This expression has type 'void' and can't be used.
  bool pop(BuildContext context) => Navigator.pop(context);
                                              ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

**Comment by lukef** [comment] 2020-02-08 16:08
Sorry, I need more info. Please provide the information in the bug issue template.

**Comment by goldenplan** [comment] 2020-02-08 16:19
When building a project, flutter throws an error stating that the specified method in your package cannot return true.

Flutter 1.15.2 • channel dev • https://github.com/flutter/flutter.git
Framework • revision d94ff4bdbe (35 hours ago) • 2020-02-06 13:19:46 -0800
Engine • revision f34bc65bee
Tools • Dart 2.8.0 (build 2.8.0-dev.7.0 b3396cbdca)

**Comment by lukef** [comment] 2020-02-08 16:45
Dupe of #146

**Closed by lukef** 2020-02-08 16:45 UTC
Labels: information needed

**Comment by taojoe** [comment] 2020-02-09 03:06
the problem caused by using flutter dev channel, you can use beta channel or stable channel.

it's about [Navigator 2.0](https://github.com/flutter/flutter/issues/45938)
